title:              Mina's Devlog
email:              wwft09@naver.com
description:      끊임없이 배우고 성장하는 사람이 되자
author:             Mina
baseurl:            ""
url:                "https://2min0r.github.io"
repository: 2Min0r/2Min0r.github.io

theme: jekyll-theme-clean-blog

# Social Profiles
twitter_username:
github_username:    2Min0r
facebook_username:  2min0r
instagram_username: 2.min0r

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-155249700-1  # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site